version: "3.7"

services:
  example-users-api-service:
    image: typescript-svc-template:local
    build:
     context: .
     target: builder
    ports:
      - "8000:8000"
    command:
      - sh
      - -c
      - "npm start"

networks:
  default:
    name: test-net


