name: Create Release Tag Job

on:
  workflow_call:
    secrets:
      GIT_KEY:
        description: 'SSH Private Key'
        required: true
      GIT_USER:
        description: 'User identifier'
        required: true
      GIT_EMAIL:
        description: 'User email address'
        required: true
    outputs:
      VERSION:
        description: "Tagged release version"
        value: ${{ jobs.release.outputs.VERSION }}
      CHANGES:
        description: "Changelog diff between versions"
        value: ${{ jobs.release.outputs.CHANGES }}

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.output-version.outputs.version }}
      CHANGES: ${{ steps.output-changes.outputs.changes }}
    steps:
      - name: Install dependencies
        run: |
          sudo apt install -y jq
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.GIT_KEY }}
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - name: Setup Node@${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - name: Configure git
        run: | 
          git config user.email $GIT_EMAIL
          git config user.name $GIT_USER
        env:
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_USER: ${{ secrets.GIT_USER }}
      - name: Create the release
        run: |
          npm ci
          npm run release
      - name: Fetch changelog
        run: |
          git diff --no-indent-heuristic main~1 HEAD CHANGELOG.md | sed -n '/^+[^+]/ s/^+//p' > /tmp/changes
          
          CHANGES=$(cat <<EOF
          $(cat /tmp/changes)
          EOF)

          echo 'RELEASE_CHANGES<<EOF' >> $GITHUB_ENV
          # cat /tmp/changes >> $GITHUB_ENV
          echo "$CHANGES" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

          echo "RELEASE_TAG=$(cat package-lock.json | jq -r .version)" >> $GITHUB_ENV
      - name: Release info
        run: |
          echo "CHANGES INCLUDED IN THIS TAGGED RELEASE:"
          cat /tmp/changes
          echo "------------------------------"
          echo "RELEASE_CHANGES=$RELEASE_CHANGES"
          echo "RELEASE_TAG=$RELEASE_TAG"
      - name: Push the release @ v${{ env.RELEASE_TAG }}
        run: |
          git push --follow-tags
      - id: output-version
        run: echo "::set-output name=version::${{ env.RELEASE_TAG }}"
      - id: output-changes
        run: echo "::set-output name=changes::${{ env.RELEASE_CHANGES }}"
      - name: display string
        run: |
          echo "The string is: ${{ steps.output-changes.outputs.changes }}"
