name: Notify Release Job

on:
  workflow_call:
    inputs:
      PROJECT:
        description: 'Name of project'
        type: string
        required: true
      TYPE:
        description: 'Type of release Notification, e.g. Tag, Github, NPM, Docker, etc'
        type: string
        required: true
      RELEASE_VERSION:
        description: 'Release information, e.g. v{{version}}'
        type: string
        required: true
      RELEASE_URL:
        description: 'Release URL, e.g. https://github.com/{{org}}/{{repository}}/releases/tag/{{version}}'
        type: string
        required: true
      CUSTOM_MSG:
        description: 'Optional custom message'
        type: string
        required: false
    secrets:
      SLACK_BOT_TOKEN:
        description: 'Slack Bot Token'
        required: true
      SLACK_CHANEL:
        description: 'Slack channel'
        required: true

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.19.0
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        channel-id: ${{ secrets.SLACK_CHANEL }}
        # For posting a rich message using Block Kit
        payload: |
          {
            "attachments": [
              {
                "color": "#5abc54",
                "blocks": [
                    {
                        "type": "header",
                        "text": {
                            "type": "plain_text",
                            "text": "${{ inputs.PROJECT }}",
                            "emoji": true
                        }
                    },
                    {
                        "type": "divider"
                    },
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "Type: `${{ inputs.TYPE }}`\nTag: `${{ inputs.RELEASE_VERSION }}`"
                        }
                    },
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": ":shipit: ${{ inputs.RELEASE_URL }}"
                        }
                    },
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "Status: *${{ job.status }}* @ [commit](${{ github.event.head_commit.url }})"
                        },
                        "accessory": {
                            "type": "button",
                            "text": {
                                "type": "plain_text",
                                "text": "View",
                                "emoji": true
                            },
                            "value": "visit_job_btn",
                            "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                            "action_id": "button-action"
                        }
                    },
                    {
                        "type": "divider"
                    },
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "${{ inputs.CUSTOM_MSG }} "
                        }
                    }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
