name: Notify 

on:
  workflow_call:
    inputs:
      TYPE:
        description: 'Type of release Notification, e.g. Tag, Github, NPM, Docker, etc'
        type: string
        required: true
      RELEASE_TAG:
        description: 'Release information, e.g. v12.1.0, etc'
        type: string
        required: true
      RELEASE_URL:
        description: 'Release URL, e.g. http://docker/tag, etc'
        type: string
        required: true
    secrets:
      SLACK_BOT_TOKEN:
        description: 'Slack Bot Token'
        required: true
      SLACK_CHANEL:
        description: 'Slack channel'
        required: true

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.19.0
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        channel-id: ${{ secrets.SLACK_CHANEL }}
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
