name: Create Tagged Release

on:
  push:
    branches: 
      - main

jobs:
  test_lint:
    uses: modusbox/github-actions/.github/workflows/reusable-workflow.yml@main

  test_dependencies:
    uses: modusbox/github-actions/.github/workflows/testDependencyJob.yml

  test_audit:
    uses: modusbox/github-actions/.github/workflows/testAuditJob.yml

  test_unit:
    uses: modusbox/github-actions/.github/workflows/testUnitJob.yml

  test_coverage:
    uses: modusbox/github-actions/.github/workflows/testCoverageJob.yml

  test_int:
    uses: modusbox/github-actions/.github/workflows/testIntJob.yml

  release_tag:
    needs:
      - test_lint
      - test_dependencies
      - test_audit
      - test_unit
      - test_coverage
      - test_int
    uses: ./.github/workflows/createReleaseTagJob.yml
    secrets:
      GIT_KEY: ${{ secrets.PSO_GIT_KEY }}
      GIT_USER: ${{ secrets.PSO_GIT_USER }}
      GIT_EMAIL: ${{ secrets.PSO_GIT_EMAIL }}
