name: Create Tagged Release

on:
  push:
    branches: 
      - main

jobs:
  test_lint:
    uses: modusbox/github-actions/.github/workflows/testLintJob.yml@main

  test_dependencies:
    uses: modusbox/github-actions/.github/workflows/testDependencyJob.yml@main

  test_audit:
    uses: modusbox/github-actions/.github/workflows/testAuditJob.yml@main

  test_unit:
    uses: modusbox/github-actions/.github/workflows/testUnitJob.yml@main

  test_coverage:
    uses: modusbox/github-actions/.github/workflows/testCoverageJob.yml@main

  test_int:
    uses: modusbox/github-actions/.github/workflows/testIntJob.yml@main

  release_tag:
    needs:
      - test_lint
      - test_dependencies
      - test_audit
      - test_unit
      - test_coverage
      - test_int
    uses: ./.github/workflows/createReleaseTagJob.yml
    secrets:
      GIT_KEY: ${{ secrets.PSO_GIT_KEY }}
      GIT_USER: ${{ secrets.PSO_GIT_USER }}
      GIT_EMAIL: ${{ secrets.PSO_GIT_EMAIL }}

  notify_tag:
    needs:
      - release_tag
    uses: ./.github/workflows/notiyReleaseJob.yml 
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANEL: ${{ secrets.SLACK_CHANNEL_PSO_RELEASE }}

  # release_gh:
  #   needs:
  #     - release_tag
  #   uses: ./.github/workflows/createReleaseGHJob.yml
