name: Create Tagged Release

on:
  push:
    branches: 
      - main

jobs:
  test_lint:
    uses: ./.github/workflows/testLintJob.yml

  test_dependencies:
    uses: ./.github/workflows/testDependencyJob.yml

  test_audit:
    uses: ./.github/workflows/testAuditJob.yml

  test_unit:
    uses: ./.github/workflows/testUnitJob.yml

  test_coverage:
    uses: ./.github/workflows/testCoverageJob.yml

  test_int:
    uses: ./.github/workflows/testIntJob.yml

  release_tag:
    needs:
      - test_lint
      - test_dependencies
      - test_audit
      - test_unit
      - test_coverage
      - test_int
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - name: Setup Node@${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - name: Configure git
        run: | 
          git config user.name "${{ github.event.pusher.name }}"
          git config user.email "${{ github.event.pusher.email }}"     
      - name: Create the release      
        run: |
          npm ci
          npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push the release
        run: git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
