name: Create Github Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Create Release
    uses: ./.github/workflows/createReleaseGHJob.yml
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
